# components/schemas/Product.yaml
type: object
properties:
  id:
    type: integer
    format: int64
    description: 商品ID
    readOnly: true
    example: 101
  name:
    type: string
    description: 商品名
    example: "高機能ワイヤレスイヤホン"
  description:
    type: string
    description: 商品説明
    example: "ノイズキャンセリング機能付きの最新モデルです。"
  price:
    type: integer
    format: int32
    description: 価格 (円)
    example: 15000
  stock:
    type: integer
    format: int32
    description: 在庫数
    example: 100
  image_url:
    type: string
    format: url
    nullable: true
    description: 商品画像URL
    example: "https://example.com/images/earphone.jpg"
  created_at:
    type: string
    format: date-time
    description: 作成日時
    readOnly: true
  updated_at:
    type: string
    format: date-time
    description: 更新日時
    readOnly: true
required:
  - name
  - price
  - stock
